[project]
name = "amiet-self-noise"
version = "0.1.0"
description = "Airfoil trailing edge noise computation code. GMC729 final project"
author = ["Enrico Foglia", "Odyssée Cadoret"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "scipy>=1.16.0",
]
